home:
  path: /
  controller: App\Controller\HomeController::index
vetements:
  path: /vetements
  controller: App\Controller\VetementsController::index

accessoires:
  path: /accessoires
  controller: App\Controller\AccessoiresController::index

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
